//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileRecord
    {
        public int Id { get; set; }
        public string Uri { get; set; }
        public MediaType MediaType { get; set; }
    
        public virtual ArticleRecord ArticleRecord { get; set; }
        public virtual UserRecord UserRecord { get; set; }
    }
}
