//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuide
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PermGuideContainer : DbContext
    {
        public PermGuideContainer()
            : base("name=PermGuideContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserRecord> UserRecordSet { get; set; }
        public virtual DbSet<ReviewRecord> ReviewRecordSet { get; set; }
        public virtual DbSet<FileRecord> FileRecordSet { get; set; }
        public virtual DbSet<RegionRecord> RegionRecordSet { get; set; }
        public virtual DbSet<TimetableRecord> TimetableRecordSet { get; set; }
        public virtual DbSet<ContentRecord> ContentRecordSet { get; set; }
    }
}
