//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermGuide
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRecord
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Mark { get; set; }
    
        public virtual UserRecord UserRecord { get; set; }
        public virtual ContentRecord ContentRecord { get; set; }
    }
}
